apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
  
    metadata:
      labels:
        app: frontend

    spec:

      containers:

      - name: frontend

        # local onde irá procurar a imagem
        # image: felipefavarin/projetok8s-frontend:1.0
        image: projetok8s-frontend:1.0

        # se o kubernetes irá buscar a imagem localmente ou via Docker Hub
        # caso a imagem esteja no docker hub, necessário usar na imagem o nome de usuário
        imagePullPolicy: Never

        ports:
        - containerPort: 80