apiVersion: v1
kind: Secret

metadata:
  name: db-secret

# Tipo padrão para objetos do tipo Secret
type: Opaque

stringData:
  # no terminal
  # echo -n "admin" | base64

  # POSTGRES_USER: admin
  POSTGRES_USER: YWRtaW4=

  # POSTGRES_PASSWORD: admin  
  POSTGRES_PASSWORD: YWRtaW4=